// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp3;

namespace Tp3.Migrations.MyContextReservaMigrations
{
    [DbContext(typeof(MyContextReserva))]
    [Migration("20210619220337_Reserva")]
    partial class Reserva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tp3.Reserva", b =>
                {
                    b.Property<int>("pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fdesde")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("fhasta")
                        .HasColumnType("datetime");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("personaint")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.Property<int>("propiedadint")
                        .HasColumnType("int");

                    b.HasKey("pk");

                    b.ToTable("Reserva");
                });
#pragma warning restore 612, 618
        }
    }
}
