// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp3;

namespace Tp3.Migrations.MyContextAlojamientoMigrations
{
    [DbContext(typeof(MyContextAlojamiento))]
    partial class MyContextAlojamientoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tp3.Alojamiento", b =>
                {
                    b.Property<int>("pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("barrio")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("baños")
                        .HasColumnType("int");

                    b.Property<int>("cantPersonas")
                        .HasColumnType("int");

                    b.Property<string>("ciudad")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.Property<int>("habitaciones")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("precioDia")
                        .HasColumnType("int");

                    b.Property<int>("precioPorPersona")
                        .HasColumnType("int");

                    b.Property<string>("tipo")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("tv")
                        .HasColumnType("bit");

                    b.HasKey("pk");

                    b.ToTable("Alojamientos");
                });
#pragma warning restore 612, 618
        }
    }
}
